/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aceprogramming.koans.non.repeated;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
